### ISSUE TITLE
string(60) "The registration token is not a valid FCM registration token"

### ISSUE THREAD

**Issue by StandaLepi** [frostcodes/php-fcm-v1-push-notification-for-b4a-and-b4i#1]
When I ran the php script, I obtained the message from the title. I downloaded my service accout via the tutorial. What's wrong? Thank you. Sorry for my english.

**Comment by Nume1977** [comment]
Same problem here. Just installed the library and it fails.

**Comment by frostcodes** [comment]
> When I ran the php script, I obtained the message from the title. I downloaded my service accout via the tutorial. What's wrong? Thank you. Sorry for my english.

Hi,
Sorry for my late reply, I had some issues with my GitHub login.

You need to follow this tutorial by Erel first:
https://www.b4x.com/android/forum/threads/b4x-firebase-push-notifications-2023.148715/

After that, simply download your service account JSON file and move it to the folder of the PHP code. If you use this code in a public directory, please move it to a private folder and edit the path in the "firebase.utils.php" file.

You can comment out the token section if you are using only topics.
Let me know if you still face any issues after this.

**Comment by frostcodes** [comment]
> Same problem here. Just installed the library and it fails.

What error do you get ?

**Comment by Nume1977** [comment]
> > Same problem here. Just installed the library and it fails.
> 
> What error do you get ?

Same exact error: string(60) "The registration token is not a valid FCM registration token"

The service account json is correct, it works with B4J.

**Comment by frostcodes** [comment]
It seems like you are only using FCM topics to send notifications. Comment out this code in firebase.utils.php, and it should work.

https://github.com/frostcodes/php-fcm-v1-push-notification-for-b4a-and-b4i/blob/7e654febb1ad2fd34722fb7959c1e79ea146b4b3/firebase.utils.php#L133C1-L142C153
